### GENERAL SETTINGS ###

# Site settings
title: Boxupp
keywords: "Boxupp by Paxcel Technologies"
description: Boxupp by Paxcel Technologies, India allows you to create and manage Development Environments with easy Provisioning and leverage immense power of DevOps tools.

scss:
  style: compressed

nav:
- page: Home
  permalink: "#top"
  id: top-link
  icon: fa-home
  linktype: 1

- page: Technologies
  permalink: "#technologies"
  id: technologies-link
  icon: fa-cogs
  linktype: 1  

- page: Downloads
  permalink: "#downloads"
  id: downloads-link
  icon: fa-download
  linktype: 1  
  
- page:  Overview
  permalink: "#overview"
  id:  Overview-link
  icon: fa-eye
  linktype: 1
  
- page: Why Boxupp
  permalink: "#why"
  id: why-link
  icon: fa-question-circle
  linktype: 1
  
- page: Features
  permalink: "#features"
  id: features-link
  icon: fa-umbrella
  linktype: 1
  
- page: Get Started
  permalink: "#started"
  id: started-link
  icon: fa-clock-o
  linktype: 1
  
- page: Developers
  permalink: "#developers"
  id: developers-link
  icon:  fa-code
  linktype: 1
 
- page: Blog
  permalink: "#blog"
  id: blog-link
  icon: fa-picture-o
  linktype: 1
  
- page: Case Studies
  permalink: /case-studies.html
  id: top-link
  icon:  fa-book
  linktype: 0